CREATE TABLE DuelMatches (
    MatchID INT IDENTITY(1,1) PRIMARY KEY,
    Player1ID INT FOREIGN KEY REFERENCES Users(UserID),
    Player2ID INT FOREIGN KEY REFERENCES Users(UserID),
    WinnerID INT FOREIGN KEY REFERENCES Users(UserID) NULL,
    PuzzleType VARCHAR(10) NOT NULL,
    MatchDate DATETIME DEFAULT GETDATE()
);