name: Trigger auto deployment for rubik-bot

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/rubik-bot-AutoDeployTrigger-99d0a300-31af-4df8-98b4-3f562441aef8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RUBIKBOT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RUBIKBOT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RUBIKBOT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.RUBIKBOT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RUBIKBOT_REGISTRY_PASSWORD }}
          containerAppName: rubik-bot
          resourceGroup: rubik_bot
          imageToBuild: timhmn/rubik-bot:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


